export enum GalleryActionTypes {
  LoadGalleries = '[Gallery] Load Galleries',
  AddGallery = '[Gallery] Add Gallery',
  UpsertGallery = '[Gallery] Upsert Gallery',
  AddGalleries = '[Gallery] Add Galleries',
  UpsertGalleries = '[Gallery] Upsert Galleries',
  UpdateGallery = '[Gallery] Update Gallery',
  UpdateGalleries = '[Gallery] Update Galleries',
  DeleteGallery = '[Gallery] Delete Gallery',
  DeleteGalleries = '[Gallery] Delete Galleries',
  ClearGalleries = '[Gallery] Clear Galleries',
  GetGalleries = '[Gallery] GetGalleries',
  GetMyGalleries = '[Gallery] GetMyGalleries',
  GetGallery = '[Gallery] GetGallery',
  LoadGallerySuccess = '[Gallery] LoadGallerySuccess',
  GalleryFailure = '[Gallery] LoadGalleryFailure',
  SetGalleryPrice = '[Gallery] SetPrice',
  SetGalleryPriceSuccess = '[Gallery] SetPriceSuccess',
  SetGalleryPriceFail = '[Gallery] SetPriceFail',
  SetGalleryPriceSendToDb = '[Gallery] SetPriceSendToDb',
  SetGalleryPriceSendToDBSuccess = '[Gallery] SetPriceSendToDBSuccess',
  SetGalleryPriceSendToDbFail = '[Gallery] SetPriceSendToDbFail',
  BuyGallery = '[Gallery] BuyGallery',
  BuyGallerySuccess = '[Gallery] BuyGallerySuccess',
  CheckGalleryOwner = '[Gallery] CheckGalleryOwner',
}
